### 用户登录
// @no-log
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "username": "how2j",
  "password": "how2j.online"
}

> {% client.global.set("auth_token", response.body.data.access_token); %}

### POST upload .txt file (single)
// @no-log
#POST http://localhost:8000/api/v1/file/upload
POST http://localhost:8000/api/v1/file/upload?upload_type=single
Content-Type: multipart/form-data;boundary=boundaryForm
Authorization: Bearer {{auth_token}}

--boundaryForm
Content-Disposition: form-data;name="file";filename="upload_file_1.txt"
Content-Type: multipart/form-data

#文件地址(与.http文件同目录同级或者后续二进制流)
< upload_file_1.txt
--boundaryForm--


### POST upload .png file (single)
// @no-log
#POST http://localhost:8000/api/v1/file/upload
POST http://localhost:8000/api/v1/file/upload?upload_type=single
Content-Type: multipart/form-data;boundary=boundaryForm
Authorization: Bearer {{auth_token}}

--boundaryForm
Content-Disposition: form-data;name="file";filename="music.png"
Content-Type: multipart/form-data

#文件地址(与.http文件同目录同级或者后续二进制流)
< music.png
--boundaryForm--



### POST upload file (multiple)
# curl -X POST http://localhost:8000/api/v1/file/upload  -F "file=upload_file_1.txt"  -F "file=upload_file_2.txt"
// @no-log
POST http://localhost:8000/api/v1/file/upload?upload_type=multiple
Content-Type: multipart/form-data; boundary=--WebAppBoundary;
Authorization: Bearer {{auth_token}}
Accept-Encoding: gzip, deflate, br

----WebAppBoundary;
Content-Disposition: form-data; name="file"; filename="upload_file_1.txt";

< upload_file_1.txt
----WebAppBoundary;
Content-Disposition: form-data; name="file1"; filename="upload_file_2.txt";

< upload_file_2.txt
----WebAppBoundary--

###





