### 创建 系统平台
POST http://localhost:8000/api/v1/platform/create
Content-Type: application/json

{
  "platform_name": "后台管理系统",
  "platform_url": "https://127.0.0.1:5217",
  "is_enable": 1
}

### 更新 系统平台
PATCH http://localhost:8000/api/v1/platform/update
Content-Type: application/json

{
  "id": "7279442665408774144",
  "platform_name": "how2j",
  "version": "1.0"
}

### 获取 系统平台 列表
GET http://localhost:8000/api/v1/platform/list

### 删除
DELETE http://localhost:8000/api/v1/platform/delete/123