### 创建用户
// @no-log
POST http://localhost:8000/api/v1/user/create
Content-Type: application/json

{
  "username": "how2j",
  "email": "how2j.online@online.com",
  "password": "how2j.online"
}

### 用户登录
// @no-log
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "username": "how2j"
}

### 获取用户列表
// @no-log
GET http://localhost:8000/api/v1/user/list


