### 创建用户
###{
###  "username": "admin",
###  "email": "admin@online.com",
###  "password": "1234567"
###}
// @no-log
POST http://localhost:8000/api/v1/user/create
Content-Type: application/json

{
  "username": "how2j",
  "email": "how2j.online@online.com",
  "password": "how2j.online"
}

### 用户登录
// @no-log
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
  "username": "how2j",
  "password": "how2j.online"
}

> {% client.global.set("auth_token", response.body.data.access_token); %}

### 用户注销
// @no-log
DELETE http://localhost:8000/api/v1/user/del
Authorization: Bearer {{auth_token}}

### 用户恢复
// @no-log
PATCH http://localhost:8000/api/v1/user/restore?email=how2j.online@online.com

### 更新数据
// @no-log
PATCH http://localhost:8000/api/v1/user/update
Content-Type: application/json
Authorization: Bearer {{auth_token}}


{
  "phone": "8888888888"
}



### 获取用户列表
// @no-log
GET http://localhost:8000/api/v1/user/list
Authorization: Bearer {{auth_token}}


