port: '8000'
mysql:
  host: '172.22.156.47'
  port: '3306'
  name: 'hi_chat'
  user: 'root'
  password: 'how2j.online'
redis:
  host: '172.22.156.47'
  port: '6379'
  password: 'how2j.online'

log:
  level: 'info' # 日志等级
  root_dir: './cache/logs' # 日志根目录
  filename: 'app.log' # 日志文件名称
  format: json # 写入格式 可选json | console
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩
