# app settings
app:
  name: "Hi Chat"
  env: "dev"
  host: "127.0.0.1"
  cacheType: "redis"


# http server settings
http:
  port: 8077
  timeout: 0

# database setting
database:
  driver: "mysql"
  mysql:
    dsn: "root:how2j.online@(localhost:3306)/hi_chat?parseTime=true&loc=Local&charset=utf8,utf8mb4"
    enableLog: true         # whether to turn on printing of all logs
    maxIdleConns: 10        # set the maximum amount connections in the idle connection pool
    maxOpenConns: 100       # set the maximum amount open database connections
    connMaxLifetime: 10     # Set the maximum time for which the connection can be reused, in minutes
    #slavesDsn: NO.  sets slaves mysql dsn, array type
    #  — “your slave dsn 1”
    #  — “your slave dsn 2”
    #mastersDsn: NO.  sets masters mysql dsn, array type, non-required field, if there is only one master, there is no need to set the mastersDsn field, the default dsn field is mysql master.
    #  — “your master dsn”

# redis settings
redis:
  dsn: "default:how2j.online@localhost:6379/0"
  dialTimeout: 10
  readTimeout: 2
  writeTimeout: 2

# logger settings
logger:
  level: "info" # output log levels debug, info, warn, error, default is debug
  format: "console" # output format, console or json, default is console
  isSave: false # false:output to terminal, true:output to file, default is false.
  logFileConfig: # Effective when isSave=true
    filename: "out.log"
    maxSize: 20 # Maximum file size (MB, default is 10MB)
    maxBackups: 50 # Maximum amount old files to retain (default is 100)
    maxAge: 15 # Maximum amount days to retain old files (default is 30 days)
    isCompression: true # Whether to compress/archive old files (default is false)

