# app settings
app:
  name: "Hi Chat"
  env: "dev"
  host: "127.0.0.1"

# http server settings
http:
  port: 8077
  timeout: 0

# database setting
database:
  driver: "mysql"
  mysql:
    dsn: "root:123456@(192.168.3.37:3306)/account?parseTime=true&loc=Local&charset=utf8,utf8mb4"
    enableLog: true

# redis settings
redis:
  dsn: "default:123456@192.168.3.37:6379/0"
  dialTimeout: 10
  readTimeout: 2
  writeTimeout: 2